import { Rocket, Database, Smartphone } from 'lucide-react'
import { supabase } from './supabase'

const APP_NAME = "leetcode-study-150"
const DESCRIPTION = "A coding test practice app based on LeetCode Top Interview 150 with concept study (Easy) and practice (Medium) modes, including visualizations."

const features = [
  ['Telegram first', '핸드폰에서 요청하고 바로 수정/배포하는 흐름을 전제로 만든 앱입니다.', Smartphone],
  ['Vercel deploy', 'GitHub push 이후 Vercel에서 웹 앱으로 배포됩니다.', Rocket],
  ['Supabase ready', '환경변수가 있으면 Supabase 클라이언트가 즉시 준비됩니다.', Database],
]

export default function App() {
  return (
    <main className="shell">
      <section className="panel">
        <p className="eyebrow">Generated by Telegram Claude Bot</p>
        <h1>{APP_NAME}</h1>
        <p className="lead">{DESCRIPTION}</p>
        <div className="status">
          <span className={supabase ? 'dot on' : 'dot'} />
          <span>{supabase ? 'Supabase connected' : 'Supabase env pending'}</span>
        </div>
      </section>

      <section className="grid">
        {features.map(([title, body, Icon]) => (
          <article className="card" key={title}>
            <Icon size={22} strokeWidth={1.8} />
            <h2>{title}</h2>
            <p>{body}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
